name: Build

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token }}
      - name: Get Latest Version
        id: latest
        uses: gregziegan/fetch-latest-release@v2.0.0
      - name: Calculate Next Version
        id: calculate
        uses: paulhatch/semantic-version@v5.3.0
        with:
          version_format: "${major}.${minor}.${patch}"
      - name: Determine Next Version
        if: ${{ contains(steps.latest.outputs.tag_name, '.') }}
        id: version
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ contains(steps.latest.outputs.name, '.') }}
          if_true: ${{ steps.calculate.outputs.version }}
          if_false: '0.0.1'
      - name: Remove Leading "v" from Latest Version
        if: ${{ contains(steps.latest.outputs.name, '.') }}
        id: latest_clean
        run: |
          export version=$(echo ${{ steps.latest.outputs.name }} | sed 's/^v//')
          echo ::set-output name=name::$version
      - name: Commit Version Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Update version to v${{ steps.version.outputs.value }}"
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: v${{ steps.version.outputs.value }}
          name: v${{ steps.version.outputs.value }}
